project_name: Global SAR Ship-Sea Classification
classes:
  - ship
  - sea
paths:
  raw_data: data/raw
  processed_data: data/processed
splits:
  train: 0.7
  val: 0.15
  test: 0.15
image:
  size: 224
  channels: 3
